# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Getting started'

env:
  GEMINI_API_KEY: AIzaSyA799z13y40PhVestuUhrcduK7dDjIZSUg
  
prompts:
  - "./prompts_1-10.txt"
  - "./prompts_11-20.txt"
  - "./prompts_21-30.txt"

providers:
  - google:gemini-2.5-flash


